Document: nginx-wp-config
Title: Debian nginx-wp-config Manual
Author: <insert document author here>
Abstract: This manual describes what nginx-wp-config is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nginx-wp-config/nginx-wp-config.sgml.gz

Format: postscript
Files: /usr/share/doc/nginx-wp-config/nginx-wp-config.ps.gz

Format: text
Files: /usr/share/doc/nginx-wp-config/nginx-wp-config.text.gz

Format: HTML
Index: /usr/share/doc/nginx-wp-config/html/index.html
Files: /usr/share/doc/nginx-wp-config/html/*.html
