#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/nginx
- name: Remove default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  ignore_errors: yes

- name: Setup Nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/nginx.conf
    owner: root
    mode: '0644'
  notify: reload nginx