---
- hosts: reactjs_servers
  become: yes
  vars:
    project_path: "/var/www/react_app"
    repository: "https://gitlab.skillbox.ru/andrey_lagutin/deploy_react_app_to_the_cloud.git"

  tasks:
    - name: Purge conflicting packages
      apt:
        name: [nodejs, npm, node-agent-base, node-aproba]
        state: absent
        purge: yes

    - name: Download Yarn GPG key
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present

    - name: Create yarn.list file
      file:
        path: /etc/apt/sources.list.d/yarn.list
        state: touch
        owner: root
        mode: '0644'

    - name: Add repository string to yarn.list
      lineinfile:
        path: /etc/apt/sources.list.d/yarn.list
        line: 'deb http://dl.yarnpkg.com/debian/ stable main'

    - name: Add NodeSource repository
      shell: curl -fsSL https://deb.nodesource.com/setup_20.x | bash -

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install yarn, npm, and nodejs
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - yarn
        - nodejs

    - name: Set release path with timestamp
      set_fact:
        release_path: "{{ project_path }}/releases/{{ lookup('pipe','date +%Y%m%d%H%M%S') }}"

    - name: Create project directory
      file:
        path: "{{ project_path }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        recurse: yes

    - name: Create release directory
      file:
        path: "{{ release_path }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        recurse: yes

    - name: Clone repository
      git:
        repo: "{{ repository }}"
        dest: "{{ release_path }}"

    - name: Replace 'Test of revert' with internal IP address
      replace:
        path: "{{ release_path }}/src/App.js"
        regexp: 'Test of revert'
        replace: "{{ ansible_default_ipv4.address }}"

    - name: Install pm2 globally
      npm:
        name: pm2
        global: yes

    - name: YARN install
      yarn:
        path: "{{ release_path }}"

    - name: Start ReactJS application with PM2
      shell: |
        sudo setcap 'cap_net_bind_service=+ep' $(which node)
        pm2 delete ReactJS || true
        pm2 --name ReactJS start npm -- start
      args:
        chdir: "{{ release_path }}"
      environment:
        PORT: 80
        NODE_OPTIONS: "--openssl-legacy-provider"
