stages:
  - build
  - deploy

build-job:
  stage: build
  tags:
    - ubuntu
  script:
    - tar -czvf archive.tar.gz -C Introduction_to_CD/html .
  artifacts:
    paths:
      - archive.tar.gz

deploy-job:
  stage: deploy
  tags:
    - ubuntu
  script:
    - cp archive.tar.gz /var/www/html/
    - tar -xzvf /var/www/html/archive.tar.gz -C /var/www/html/ --no-same-owner --touch